### ISSUE TITLE
Issues generating images

### ISSUE THREAD

**Issue by rossman22590** [erictik/midjourney-ui#54]
I get this error

Failed to load resource: the server responded with a status of 404 (Not Found) on image command

**Comment by danilaprokoshev** [comment]
The same problem.

**Comment by rossman22590** [comment]
Fixed by rewriting code ;)

**Comment by chaeeun-seo** [comment]
@rossman22590 can you explain in more detail plz? I have the same issue.

**Comment by bvzgame** [comment]
ditto @rossman22590

**Comment by bvzgame** [comment]
> @rossman22590 can you explain in more detail plz? I have the same issue.

for anyone still having issues with this repo - i found someone that forked it and it works! shoutout @SoyZhou 
https://github.com/SoyZhou/midjourney-ui
